# Generated by Django 4.2.19 on 2025-03-03 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuLink',
        ),
    ]
